# This is for MacOSX

CFLAGS = -I /Developer/Headers/FlatCarbon/ -D_MAC_ -DPOWER -DGNU_C -DKARBON -O
AR = ar
RANLIB = ranlib

OBJECTS = \
	backend.o backendsupport.o buildtree.o cocl.o \
	codegen1.o codegen2.o codegen3.o codegen.o \
	compiler.o comsupport.o dbprint.o instructions.o optimisations.o \
	pattern_match_2.o sa.o set_scope_numbers.o settings.o statesgen.o \
	mac_io.o path_cache.o

backend.a: $(OBJECTS)
	$(AR) cur backend.a $(OBJECTS)
	$(RANLIB) backend.a
